[project]
name = "rag"
version = "0.1.0"
description = "RAG application"
readme = "README.md"
authors = [
    { name = "Sathvik2210", email = "sathvik2210@gmail.com" }
]
requires-python = ">=3.11"

dependencies = [
    "fastapi",
    "uvicorn",

    "chromadb",

    "langchain",
    "langchain-community",
    "langchain-text-splitters",
    "langchain-groq",

    "sentence-transformers",
    "transformers",
    "torch",

    "pymupdf",
    "pypdf",

    "scikit-learn",
    "numpy",

    "groq",
    "python-dotenv",
    "tqdm",
]

[project.scripts]
rag = "rag:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"